---
title: "Predicting United States County-Level COVID-19 Mortality Risk using Environmental, Behavioral, and Socioeconomic Factors"
author: "Xiang Bai, Jennifer Dai, Justin Farmer, Yu Fu, Steven Tang"
date: "12/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview and Motivation: 
This project examines the relationship between long-term exposure to air pollution and the risk of mortality from COVID-19. To do so in a relatively short time frame, we used county-level data from a well-documented and publicly available data set created by researchers at HSPH. We were motivated to do this project as COVID-19 continues to devastate much of the world and the patterning of deaths continue to be starkly inequitable. Within the US, these disparities exist across racial and socioeconomic lines and mortality rates vary considerably across different geographic locations. Researchers and local policymakers are still facing urgent public health questions to mitigate the disease’s burden on the population level, particularly as new variants threaten to weaken the efficacy of vaccines. We feel that it is important to take into consideration how the long-term environmental and socioeconomic circumstances of different areas help predict the severity of the pandemic (measured in deaths from COIVD-19) for a given community. This could better allow policymakers to tailor their response to best serve communities likely to be hit the hardest by future waves of COVID-19 and other similar diseases in the future. 

### Objectives
1. To investigate the effect of long-term exposure to PM2.5 on COVID-19 outcomes.
2. To use machine learning to predict whether or not a county will have above average  COVID-19 deaths from 03/22/20 to 10/31/21. 
3. To understand if the trend in county-level COVID-19 deaths associated with long-term exposure to air pollution are the same before the introduction of vaccines as they are for the full period. 

## Related Work: 
According to data from Johns Hopkins University, more than 353,000 coronavirus deaths have been reported this year. Many of the pre-existing conditions that increase the risk of COVID-19 mortality, including asthma and other lung conditions, are the same underlying conditions exacerbated by long-term exposure to air pollution. One recent project that explored the relationship between PM2.5 and COVID-19 deaths was done by Wu et al. As mentioned above, this work directly inspired our project. A link to it can be found here https://github.com/wxwx1993/PM_COVID. In short, that study indicates that higher historical PM2.5 exposures are positively associated with higher county-level COVID-19 mortality rates after accounting for many area-level confounders. However, it only examined data up to mid-June 2020, which could be biased and of lower generalizability since it only reflects those who died in the first wave pf COVID-19 cases in the US. 

## Initial Questions: 
We first wanted to understand how different environmental and socioeconomic factors vary spatially across the United States. In particular, we were inspired by the Wu et al paper to examine possible effects of PM2.5 levels across counties as these often reflect the long-term circumstances of a community. We quickly became interested in understanding if the effects identified by Wu et al continued to hold after the time period that they examined. That is, does the long-term PM2.5 exposure only predict places that will have deaths sooner or does it also help predict the total number of deaths over the course of a longer period (through the date of our study conceptualization, 10/31/21)? We also wanted to identify if these models change at all when we compare the period before widespread availalbity of vaccination to the full data set. 

## Data: 
Our data was taken from various places, building upon the work by Wu et al. These sources include the Johns Hopkins University the Center for Systems Science and Engineering (JHU-CSSE), the Atmospheric Composition Analysis Group, the 2000 and 2010 US censuses, the 2005–2016 American Community Surveys, and the 2009–2016 CDC Compressed Mortality File. 

The data set includes all continental U.S. counties which had reported at least one COVID-19 death and have valid monthly PM2.5 data from 2000-2018. Data sources are all publicly available(https://github.com/wxwx1993/PM_COVID). 

The county-level COVID-19 deaths count is extracted from JHU-CSSE Coronavirus Resource Center (https://coronavirus.jhu.edu/). 

Averaged PM2.5 concentration across the period 2000-2018 was linked to each county by leveraging data from Atmospheric Composition Analysis Group (https://sites.wustl.edu/acag/).

We used extensive web scraping to accumulate all of this data before integrating into a single clean data set. A full documented version of this webscrapping was created by Steven and can be found in the RMarkdown file WebScraping_1211.Rmd in this project repository. 

## Exploratory Analysis: 
What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions?

We first created visualizations depicting maps of the US shaded by various factors that we considered to be potentially important in predicting deaths from COVID-19 on the county level. Upon examining these maps, we decided to create a Shiny App to allow others to see how these different covariates vary throughout the country and on a more basic level be able to hone in on places that have the most deaths. This app can be found here https://jfarmer13.shinyapps.io/County-Level/. We also created graphics depicting the correlation between each factor and COVID-19 mortality to get a feel for which factors are potentially the most relevant to predict COIVD-19 deaths on the county level. We took these into consideration when running linear and logistic models that helped us better understand the associations between these factors independently after controlling for the others. These models helped us highlight average summer temperature, high school graduation rates, median home value, median household income, and average winter temperature as important factors to consider in addition to PM2.5. 

This exploration also made us consider that trying to predict a continuous number of deaths per 100,000 in the county would be difficult as there were so many relevant factors. We also felt that the exact number of deaths is likely less important than being able to provide policymakers the chance that a specific county will be above average for COVID-19 mortality. Therefore, we decided to prioritize creating classification models of a binary outcome (being above the mean) rather than emphasizing the  creation continuous predictive models. We ultimately decided to try to create continuous models for good measure and to test if our hunch that these models may not perform well was accurate. 

## Final Analysis:
Our final analysis built on the examination of feature analysis that we pulled from the Shiny App and the regression models. We used two different machine learning approaches, Support Vector Regression and Random Forests, to predict the chance that a county would be classified as above average for mortality and compared these predicted classifications to the true ones in our data both for our full study period (03/2020-10/2021) and well as only before the introduction of the vaccine (03/2020-04/2021). We also used these models to predict the continuous number of deaths in the county for both time windows. 

### Support Vector Regression: 
For feature selection, we referred to the references of the data as well as the cited resources for context and information. Furthermore, the correlations of covariates on death rate were assessed as well as the use of LASSO regression on features for shrinkage. Election to use support vector  regression ([SVR](https://towardsdatascience.com/an-introduction-to-support-vector-regression-svr-a3ebc1672c2)) model resulted in predictions of death rates for counties, where we explored using all features in our data as well as select variables notably, temperature patterns, PM 2.5 exposure and others. We found that the predicted rates while acceptable in a range were low performance when benchmarked to test set values with suboptimal R-squared values. Further, implementing binary outcome for prediction also with SVR yielded more satisfatory results where the balanced accuracy achieved was higher than 70%, while maintaining consistent specificity and sensitivity values. The full code for this analysis is contained within the file XB_MLsection.Rmd in the project repository. 

### Random Forest: 
Since Random Forests can calculate feature importance and outperform linear models when relationship between outcome and predictors is complex and non-linear, we also used Random Forest models to predict COVID-19 mortality rate and explore the importance of predictors in our model (detailed analysis see “Yu Fu Random Forest.Rmd” and “Yu-Fu-Random-Forest.html” ). We compared variable importance from the random forest models fitted to the data before the introduction of vaccination and the full data. In this sense, we are able to examine if PM 2.5 continue to be an important predictor of COVID-19 mortality rate over time. Additionally, to improve model performance, we used binary outcome for classification with Random Forest models and explored variable importance. We chose the final model using important predictors to achieve high accuracy, sensitivity, and specificity. The full code for this analysis is contained within the file Yu Fu Random Forest.Rmd in the project repository. 


### Conclusions: 




